name: flutter_side_menu
description: Flutter's full customizable side menu has been used as a directory for Related Pages, Navigation Items, Filter side and more
version: 0.1.1
homepage: https://github.com/resfandiari/flutter_side_menu

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

