name: flutter_side_menu
description: Flutter's full customizable side menu has been used as a directory for Related Pages, Navigation Items, Filter side and more
version: 0.4.0
homepage: https://github.com/resfandiari/flutter_side_menu

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

